---
version: "3.7"
services:
  pogsmithy-discord-test:
    build: .
    image: gunsmithy/personal:pogsmithy-discord-test
    container_name: pogsmithy-discord-test
    environment:
      POGSMITHY_DISCORD_SECRET_FILE: /run/secrets/pogsmithy_discord_secret
    secrets:
      - pogsmithy_discord_secret
    restart: unless-stopped

secrets:
  pogsmithy_discord_secret:
    file: BotSecret.txt
